spring:
  datasource:
    url: jdbc:mysql://localhost:3306/saver?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
  config:
    import:
      - application-security.yaml

exp:
  init: 20
  increase: 25