spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sangjinb609@gmail.com
    password: oajj hknp atxe atur
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true