spring:
  sql:
    init:
      mode: always

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
  config:
    import:
      - application-security.yaml

exp:
  init: 20
  increase: 25