spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: sangjinb609@gmail.com
    password: oajj hknp atxe atur
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  security:
    oauth2:
      client:
        provider:
          naver:
            user-info-uri: https://openapi.naver.com/v1/nid/me
          kakao:
            user-info-uri: https://kapi.kakao.com/v2/user/me

server:
  servlet:
    session:
      timeout: 1800
      tracking-modes: cookie
